version: "2"

services:
  nodeapp:
    build: ./app
    container_name: "app"
    networks:
      - rethink-net
    environment:
      - 'dbservers=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb4;rethinkdb5'
    links:
      - rethinkdb1
      - rethinkdb2
      - rethinkdb3
      - rethinkdb4
      - rethinkdb5
    ports:
      - "8099:8099"

  rethinkdb1:
    build: ./rethinkdb
    container_name: "rethinkdb1"
    environment:
      - "DBCLUSTERHOSTS=rethinkdb2;rethinkdb3;rethinkdb4;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb1 --bind all"
    hostname: rethinkdb1
    networks:
      - rethink-net
    ports:
      - "8081:8080"
      - "38015:28015"
      - "39015:29015"
    volumes:
      - ./data/rethinkdb/rdb1:/data

  rethinkdb2:
    build: ./rethinkdb
    container_name: "rethinkdb2"
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb3;rethinkdb4;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb2 --bind all"
    hostname: rethinkdb2
    networks:
      - rethink-net
    ports:
      - "8082:8080"
    volumes:
      - ./data/rethinkdb/rdb2:/data

  rethinkdb3:
    build: ./rethinkdb
    container_name: "rethinkdb3"
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb2;rethinkdb4;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb3 --bind all"
    hostname: rethinkdb3
    networks:
      - rethink-net
    ports:
      - "8083:8080"
    volumes:
      - ./data/rethinkdb/rdb3:/data

  rethinkdb4:
    build: ./rethinkdb
    container_name: "rethinkdb4"
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb4 --bind all"
    hostname: rethinkdb4
    networks:
      - rethink-net
    ports:
      - "8084:8080"
    volumes:
      - ./data/rethinkdb/rdb4:/data

  rethinkdb5:
    build: ./rethinkdb
    container_name: "rethinkdb5"
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb4"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb5 --bind all"
    hostname: rethinkdb5
    networks:
      - rethink-net
    ports:
      - "8085:8080"
    volumes:
      - ./data/rethinkdb/rdb5:/data

networks:
  rethink-net:
    driver: bridge
